spring:
  application:
    name: hotel-booking-service
  jpa:
    generate-ddl: true
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    #url: jdbc:postgresql://postgres:5432/booking_db
    url: jdbc:postgresql://localhost:5432/booking_db
    username: postgres
    password: postgres
    hikari:
      schema: user_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS user_schema
      connection-timeout: 10000