spring:
  application:
    name: hotel-booking-service
  jpa:
    generate-ddl: true
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://postgres:5432/booking_db
    #url: jdbc:postgresql://localhost:5432/booking_db
    username: postgres
    password: postgres
    hikari:
      schema: user_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS user_schema
      connection-timeout: 10000

  data:
    mongodb:
      uri: mongodb://root:root@mongodb:27017/statistics_database?authSource=admin
      #uri: mongodb://root:root@localhost:27017/statistics_database?authSource=admin

  kafka:
    bootstrap-servers: kafka:9092
    #bootstrap-servers: localhost:9092
    consumer:
      group-id: stats
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    listener:
      missing-topics-fatal: false
server:
  port: 8080

app:
  kafka:
    userRegistrations: "user-registrations"
    roomBookings: "room-bookings"
    groupId: "stats"